services:
  app-prod:
    build: .
    image: sistema-receitas:latest
    container_name: app-prod
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      DB_HOST: mysql-prod
      DB_USER: root
      DB_PASS: root_pass
      DB_NAME: db_receitas
    depends_on:
      - mysql-prod
    networks:
      - receitas-net

  mysql-prod:
    image: mysql:8.0
    container_name: mysql-prod
    restart: unless-stopped
    command: --skip-name-resolve
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: db_receitas
    volumes:
      - mysql-prod-data:/var/lib/mysql
    networks:
      - receitas-net

volumes:
  mysql-prod-data:

networks:
  receitas-net:
    external: true
