sonar.projectKey=rafamuller5_sistema-receitas
sonar.organization=rafamuller5
sonar.projectName=Sistema de Receitas
sonar.sources=.
sonar.exclusions=vendor/**,tests/**,reports/**,.github/**
sonar.php.coverage.reportPaths=reports/clover.xml
sonar.php.tests.reportPath=reports/junit-report.xml
sonar.tests=tests
sonar.test.inclusions=**/*ReceitaTest.php,**/*.spec.js